version: '3.8'

services:

  celery-worker:
    container_name: celery_worker_container
    build: .
    command: celery -A tasks.celery_app:celery_app worker -E -l info
    restart: always
    depends_on:
      - redis
    links:
      - redis

  celery-beat:
    container_name: celery_beat_container
    build: .
    command: celery -A tasks.celery_app:celery_app beat -l info
    restart: always
    depends_on:
      - redis
      - celery-worker
    links:
      - redis
      - celery-worker


  redis:
    image: redis:latest
    container_name: redis_container
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        redis-server /usr/local/etc/redis/redis.conf
      '
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data